export type GuestModel = {
    id: number;
    tabnum: number | null;
    firstname: string;
    lastname: string;
    secondName: string;
    note: string;
    dateStart: string;
    dateFinish: string;
    flatId: number;
    flatName: string;
    hotelName: string;
    hotelId: number;
    filialName: string;
    filialId: number;
    roomId: number;
    roomName: string;
    organization: string;
    regPoMestu: boolean;
    memo: string;
    billing: string;
    reason: string;
    filialEmployee?: string;
    error?: string;
    male: boolean;
    email?: string;
    daysCount?: number;
    cost?: number;
    costByNight?: number;
    post?: string;
    checkouted?: boolean;
    contractId?: number;
    contractNumber?: string;
    bedName?: number;
    bedId?: number;
    nights?: number;
}